cordova plugin add https://github.com/pushandplay/cordova-plugin-apprate.git
cordova plugin rm org.apache.cordova.dialogs
cordova plugin add cordova-plugin-dialogs
cordova plugin add https://github.com/whiteoctober/cordova-plugin-app-version.git
cordova plugin add https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin.git
cordova plugin add cordova-plugin-camera
cordova plugin add https://github.com/VitaliiBlagodir/cordova-plugin-datepicker.git
cordova plugin add cordova-plugin-device
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git
cordova plugin add cordova-plugin-file
cordova plugin add https://github.com/pwlin/cordova-plugin-file-opener2.git
cordova plugin add https://github.com/driftyco/ionic-plugins-keyboard.git
cordova plugin add https://github.com/litehelpers/Cordova-sqlite-storage.git
cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git
cordova plugin add https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin.git
cordova plugin add cordova-plugin-screen-orientation
ionic plugin add cordova-plugin-whitelist
